GenSpectrum/dashboards

backend/.gitignore
backend/README.md
backend/build.gradle.kts
backend/dev.properties.example
backend/src/main/kotlin/org/genspectrum/dashboardsbackend/config/BackendSpringConfig.kt
backend/src/main/kotlin/org/genspectrum/dashboardsbackend/model/JacksonSerializableJsonb.kt
backend/src/main/kotlin/org/genspectrum/dashboardsbackend/model/SubscriptionModel.kt
backend/src/main/kotlin/org/genspectrum/dashboardsbackend/model/SubscriptionTable.kt
backend/src/main/resources/application.properties
backend/src/main/resources/db/migration/V1__init.sql
backend/src/test/kotlin/org/genspectrum/dashboardsbackend/TestContainerConfig.kt
backend/src/test/resources/application.properties
docker-compose.yml

resolves #74
This PR introduces a postgres backend database, which persists the subscriptions. It is provisioned with flyway and called by exposed. 
The tests run their own test database.

Notification backend persist subscriptions in database

---

backend/src/main/kotlin/org/genspectrum/dashboardsbackend/controller/ExceptionHandler.kt
backend/src/main/kotlin/org/genspectrum/dashboardsbackend/controller/SubscriptionsController.kt
backend/src/main/kotlin/org/genspectrum/dashboardsbackend/model/SubscriptionModel.kt
backend/src/main/kotlin/org/genspectrum/dashboardsbackend/model/SubscriptionTable.kt
backend/src/main/resources/db/migration/V1__init.sql
backend/src/test/kotlin/org/genspectrum/dashboardsbackend/BackendApplicationTest.kt
backend/src/test/kotlin/org/genspectrum/dashboardsbackend/controller/SubscriptionsClient.kt
backend/src/test/kotlin/org/genspectrum/dashboardsbackend/controller/SubscriptionsControllerTest.kt

notification backend get subscriptionsid

---

backend/src/main/kotlin/org/genspectrum/dashboardsbackend/controller/SubscriptionsController.kt
backend/src/main/kotlin/org/genspectrum/dashboardsbackend/model/SubscriptionModel.kt
backend/src/test/kotlin/org/genspectrum/dashboardsbackend/controller/SubscriptionsClient.kt
backend/src/test/kotlin/org/genspectrum/dashboardsbackend/controller/SubscriptionsControllerTest.kt

feat(backend): implement DELETE /subscriptions/{id}

---

backend/src/main/kotlin/org/genspectrum/dashboardsbackend/controller/InfoController.kt
backend/src/test/kotlin/org/genspectrum/dashboardsbackend/controller/InfoControllerTest.kt

I was annoyed that every time I go to localhost:8080, I see a 404 page.

feat(backend): add a welcome page on `/`

---

website/package-lock.json

This should fix the ci. Something went wrong in the package-lock.
This error was shown in the ci.
```
Error: Cannot find module @rollup/rollup-linux-arm64-musl. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory. 
```

fix(website): fix package-lock.json

---

backend/src/main/kotlin/org/genspectrum/dashboardsbackend/subscriptions/Subscription.kt
website/src/layouts/base/OrganismSelector.astro
website/src/pages/index.astro
website/src/pages/subscriptions/index.astro
website/src/routes/View.ts
website/src/routes/covid.ts
website/src/routes/h5n1.ts
website/src/routes/mpox.ts
website/src/routes/routing.ts
website/src/routes/rsvA.ts
website/src/routes/rsvB.ts
website/src/routes/westNile.ts
website/tests/config/dashboards_config.example.json

refactor: unify organism names and refactor their config

---

.github/workflows/website.yml
website/src/components/LocationTimeFilter.astro
website/src/components/VariantFilter.astro
website/src/components/VariantFilterTypes.ts
website/src/components/auth/UserDropdown.astro
website/src/components/covidView1/CollectionsList.tsx
website/src/components/covidView2/JointFilter.astro
website/src/components/rsv/RsvSequencingEffortsPage.astro
website/src/components/rsv/RsvSingleVariantPage.astro
website/src/layouts/base/ViewSelector.astro
website/src/pages/covid/compare-side-by-side.astro
website/src/pages/data.astro
website/src/pages/index.astro
website/src/pages/logout.astro
website/src/pages/west-nile/single-variant.astro
website/src/routes/View.ts
website/src/routes/covid.ts
website/src/routes/h5n1.ts
website/src/routes/mpox.ts
website/src/routes/rsvA.ts
website/src/routes/rsvB.ts
website/src/routes/westNile.ts

fix(website): activate `astro check` in ci and fix issues

---

backend/src/main/kotlin/org/genspectrum/dashboardsbackend/config/BackendSpringConfig.kt
backend/src/main/kotlin/org/genspectrum/dashboardsbackend/logging/RequestId.kt
backend/src/main/kotlin/org/genspectrum/dashboardsbackend/model/triggerevaluation/LapisClient.kt

resolves #102
This is mostly copied over from LAPIS. I also tested that the request id is handed over to LAPIS.

feat(backend): add request id to be able to trace requests

---

backend/src/main/resources/application-dashboards-dev.yaml
backend/src/main/resources/application-dashboards-prod.yaml
backend/src/main/resources/application-dashboards-staging.yaml

resolves #159
Use pathoplexus instance of LAPIS for westNile.

feat(website): use pathoplexus lapis for westNile

---

backend/src/main/resources/application-dashboards-staging.yaml

fix(backend): fix covid staging config

---

website/src/pages/404.astro
website/src/pages/500.astro

resolves #135
Creates both a custom 404 and 500 error page.

Add error page

---

website/src/pages/covid/index.astro

resolves #186
This seems to have been forgotten in #155

fix(website): covid landing page - use initialized routing object

---

backend/src/main/kotlin/org/genspectrum/dashboardsbackend/config/DashboardsConfig.kt
backend/src/main/kotlin/org/genspectrum/dashboardsbackend/model/triggerevaluation/TriggerEvaluator.kt
backend/src/main/resources/application-dashboards-dev.yaml
backend/src/main/resources/application-dashboards-prod.yaml
backend/src/main/resources/application-dashboards-staging.yaml
backend/src/test/kotlin/org/genspectrum/dashboardsbackend/model/triggerevaluation/CountTriggerEvaluatorTest.kt
backend/src/test/kotlin/org/genspectrum/dashboardsbackend/model/triggerevaluation/ProportionTriggerEvaluatorTest.kt
backend/src/test/resources/application.yaml
website/src/components/LocationTimeFilter.astro
website/src/components/rsv/RsvSequencingEffortsPage.astro
website/src/components/rsv/RsvSingleVariantPage.astro
website/src/components/subscriptions/create/FilterDisplay.tsx
website/src/config.ts
website/src/pages/covid/sequencing-efforts.astro
website/src/pages/covid/single-variant.astro
website/src/pages/flu/h5n1/sequencing-efforts.astro
website/src/pages/flu/h5n1/single-variant.astro
website/src/pages/mpox/sequencing-efforts.astro
website/src/pages/mpox/single-variant.astro
website/src/pages/west-nile/sequencing-efforts.astro
website/src/pages/west-nile/single-variant.astro
website/src/routes/covid.ts
website/src/routes/h5n1.ts
website/src/routes/mpox.ts
website/src/routes/rsvA.ts
website/src/routes/rsvB.ts
website/src/routes/westNile.ts

resolves #141
Each time LAPIS is called for WestNile an additional filter for the latest version is applied. This is necessary, because Loculus provides the whole data, including revisions, to LAPIS.

Make sure the plots only use latest versions from lapis

---

.github/workflows/website.yml
website/package-lock.json
website/package.json
website/src/components/subscriptions/backendApi/backendService.spec.ts
website/src/components/subscriptions/backendApi/backendService.ts
website/src/components/subscriptions/backendApi/querySubscriptions.ts
website/src/components/subscriptions/create/SubscriptionsCreate.tsx
website/src/components/subscriptions/overview/SubscriptionEntry.tsx
website/src/types/ProblemDetail.ts
website/src/types/Subscription.ts
website/vitest.config.js
website/vitest.setup.ts

resolves #206
Introduces unit tests for the backendService using msw and vitest. The tests are now run in ci. 
Includes also a minor refactoring: the parameters are now passed as an object to the backendService functions. This prevents mixing up userId and submissionId.

206 add unit tests for backendservice

---

website/package-lock.json
website/package.json
website/src/components/subscriptions/create/SubscriptionsCreate.tsx
website/src/components/subscriptions/overview/SubscriptionEntry.tsx
website/src/layouts/base/BaseLayout.astro

resolves #205
This PR adds toast notifications for deleting a subscription, creating a subscription and on errors for those two. Also, the "Create subscription" button now changes color on success. 
I chose to use "react-toastify", since it provided good results in loculus.
I also deactivated the "activate/deactivate" button, since this only necessary for our notification channels. This will be enabled by #171.

feat(website): show banner indication for actions #205

---

website/.env.docker
website/.env.example
website/package-lock.json
website/package.json
website/src/clientLogger.ts
website/src/components/LocationTimeFilter.astro
website/src/components/VariantFilter.astro
website/src/components/covidAnalyzeSingleVariantView/CollectionsList.tsx
website/src/components/covidCompareVariantsView/JointFilter.astro
website/src/components/subscriptions/backendApi/backendService.spec.ts
website/src/components/subscriptions/backendApi/backendService.ts
website/src/components/subscriptions/create/SubscriptionsCreate.tsx
website/src/components/subscriptions/overview/SubscriptionEntry.tsx
website/src/components/subscriptions/overview/Subscriptions.tsx
website/src/logger.ts
website/src/middleware.ts
website/src/middleware/errorMiddleware.ts
website/src/middleware/loggingMiddleware.ts
website/src/pages/500.astro
website/src/pages/api/log.ts
website/src/pages/api/subscriptions/[...path].ts
website/src/routes/covid.ts
website/src/routes/routing.ts
website/src/routes/serverSideRouting.ts
website/src/types/ProblemDetail.ts
website/src/types/logMessage.ts
website/src/util/getErrorLogMessage.ts

resolves #203
* Using https://github.com/winstonjs/winston
* For client side code, there is now `/api/log` that accepts POST requests with log messages.

feat(website): add logging

---

website/README.md

docs(website): how to use your local components

---

website/package-lock.json
website/package.json

Bumbs the version of dashboard-components to get the performance increases of the mutation over time component.

chore(website): bump version of dashboard-components

---

website/package-lock.json
website/package.json
website/src/clientLogger.ts
website/src/components/ErrorReportInstruction.tsx
website/src/components/subscriptions/create/SubscriptionsCreate.tsx
website/src/components/subscriptions/overview/SubscriptionEntry.tsx
website/src/logger.ts
website/src/pages/500.astro
website/src/pages/api/log.ts
website/src/types/logMessage.ts

resolves #201
If something unexpected happens,
- show an error id to the user
- tell the user to report that id
- log the error with that id so that we can find it in the logs
A follow-up task is providing more useful error messages to users: https://github.com/GenSpectrum/dashboards/issues/256
When an error occurs in server-side code:
When an error occurs in client-side code:

feat(website): provide instruction how to report errors

---

website/src/layouts/base/header/Navigation.tsx
website/src/pages/index.astro
website/src/types/pages.ts

refactor(website): extract /data link to constant

---

website/src/lapis/getLastUpdatedDate.spec.ts
website/src/lapis/getLastUpdatedDate.ts
website/src/layouts/OrganismPage/OrganismPageLayout.astro
website/src/middleware.ts
website/src/util/setupDayjs.ts
website/vitest.setup.ts

resolves #233
For recent dates:
For dates that are longer ago:

feat: show "last updated" dates in footer

---

website/src/views/covid.ts

fix(website): year of covid "2021" date range `dateFrom`

---

website/src/types/Organism.ts

As discussed in today's meeting

fix(website): it should be called "Mpox"

---

website/src/layouts/base/footer/FooterNavigation.astro

fix(website): make GitHub link point to repo instead of to project

---

backend/src/main/resources/application-dashboards-dev.yaml
backend/src/main/resources/application-dashboards-prod.yaml
backend/src/main/resources/application-dashboards-staging.yaml

fix: use correct location field names for west nile

---

website/src/layouts/base/header/Navigation.tsx

resolves #219
The code isn't pretty yet, but before doing that, I'd like feedback whether the solution is good enough.
I tried to stick to having a statically rendered menu (no JS there on client side)
[Bildschirmaufzeichnung vom 07.11.2024, 14:51:13.webm](https://github.com/user-attachments/assets/8c5e49c6-06b9-4bdf-be2d-127e328c7078)

219 clickable mega menu navigation

---

website/README.md
website/src/layouts/base/footer/FooterNavigation.astro
website/src/layouts/base/header/Brand.tsx

partially resolves https://github.com/GenSpectrum/dashboards/issues/279
1. Add favicon to header
2. Make footer shorter

feat(website): add favicon to header

---

website/src/pages/flu/h5n1/single-variant.astro
website/src/views/h5n1.ts

resolves #179
Adding the filter:
Adding the table to aggregated by clade:

feat(website): add clade filter and table to H5N1

---

backend/src/main/kotlin/org/genspectrum/dashboardsbackend/config/DashboardsConfig.kt
backend/src/main/resources/application-dashboards-dev.yaml
backend/src/main/resources/application-dashboards-prod.yaml
backend/src/main/resources/application-dashboards-staging.yaml
website/src/config.ts
website/src/layouts/base/header/Navigation.tsx
website/src/pages/index.astro
website/src/views/routing.ts

Resolves #282
We now show external links below the internal ones, both in the menu and the "home" page. The external links can be configured in the config.

feat(website): add browse data menu entry

---

website/src/layouts/base/footer/DataOriginLink.astro
website/src/pages/data.astro

I added a sentence to the Data Sources text and (independently( improved the positioning of the icon for external links.

feat(website): improve external link styling and data source text

---

backend/src/main/resources/application-dashboards-dev.yaml
backend/src/main/resources/application-dashboards-prod.yaml
backend/src/main/resources/application-dashboards-staging.yaml

We didn't notice in #319 that it breaks the backend.

fix(backend): bring back mpox config to fix backend startup

---

website/package-lock.json
website/package.json
website/src/components/genspectrum/GsApp.tsx
website/src/components/genspectrum/GsDateRangeSelector.tsx
website/src/components/genspectrum/GsLineageFilter.tsx
website/src/components/genspectrum/GsLocationFilter.tsx
website/src/components/genspectrum/GsMutationFilter.tsx
website/src/components/genspectrum/GsNumberSequencesOverTime.tsx
website/src/components/genspectrum/GsPrevalenceOverTime.tsx
website/src/components/genspectrum/GsTextInput.tsx
website/src/components/pageStateSelectors/BaselineSelector.tsx
website/src/components/pageStateSelectors/CompareSideBySidePageStateSelector.tsx
website/src/components/pageStateSelectors/SequencingEffortsPageStateSelector.tsx
website/src/components/pageStateSelectors/SingleVariantPageStateSelector.tsx
website/src/components/subscriptions/create/SubscriptionsCreate.tsx
website/src/layouts/base/BaseLayout.astro
website/src/pages/west-nile/single-variant.astro
website/src/util/chooseGranularityBasedOnDateRange.spec.ts
website/src/util/chooseGranularityBasedOnDateRange.ts
website/src/views/View.ts
website/src/views/covid.ts
website/src/views/h5n1.ts
website/src/views/helpers.ts
website/src/views/westNile.ts

Bumps the version of dashboards to 0.9 and fixes the issues with the breaking changes.

chore(website): bump dashboard components version to 0.9

---

website/package-lock.json
website/package.json

Move dashboard components from dev dependencies to dependencies, since we are using functions directly.

fix(website): put components into dependencies

---

website/src/pages/index.astro

I changed the landing page a tiny bit and will merge it right away.

feat(website): edit landing page text and add How to cite

---

website/package-lock.json
website/package.json

Just a quick update to get the new version of the components.

chore(website): bump dashboard components from 0.9.0 to 0.9.1

---

website/package-lock.json
website/package.json

chore(website): update dashboard components to 0.10.0

---

website/src/components/GenericCompareSideBySidePage.astro
website/src/components/pageStateSelectors/CompareSideBySidePageStateSelector.tsx
website/src/components/pageStateSelectors/SequencingEffortsPageStateSelector.tsx
website/src/components/pageStateSelectors/SingleVariantPageStateSelector.tsx
website/src/pages/flu/h5n1/compare-side-by-side.astro
website/src/pages/rsv-a/compare-side-by-side.astro
website/src/pages/rsv-b/compare-side-by-side.astro
website/src/pages/west-nile/compare-side-by-side.astro
website/src/views/PageStateHandler.ts
website/src/views/View.ts
website/src/views/covid.ts
website/src/views/h5n1.ts
website/src/views/routing.ts
website/src/views/rsvA.ts
website/src/views/rsvB.ts
website/src/views/westNile.ts

feat(website): add compare side by side view for all other organisms

---

website/src/components/ErrorReportInstruction.tsx
website/src/pages/500.astro

feat(website): add button to copy error information to clipboard

---

.github/workflows/backend.yml
.github/workflows/e2e.yml
.github/workflows/website.yml
Dockerfile_website
docker-compose.yml
website/.gitignore
website/package-lock.json
website/package.json
website/playwright.config.ts
website/tests/dataSources.spec.ts
website/tests/mainPage.spec.ts

resolves #348
I focused on getting the setup done. I just added some very basic tests - we can improve on that side later. Those tests should already have caught some of our recent issues.

test(website): add e2e test setup with playwright and some basic tests

---

backend/src/main/resources/application-dashboards-prod.yaml
backend/src/main/resources/application-dashboards-staging.yaml

chore(config): switch to new api.loculus domains

---

.github/workflows/rebaseProd.yml

build: instruct to merge update-prod-prs via merge commits

---

backend/src/main/resources/application-dashboards-dev.yaml
backend/src/main/resources/application-dashboards-prod.yaml
backend/src/main/resources/application-dashboards-staging.yaml

fix(config): only consider latest versions from our Loculus instances

---

website/src/components/rsv/RsvSequencingEffortsPage.astro
website/src/components/views/analyzeSingleVariant/GenericAnalyzeSingleVariantPage.astro
website/src/components/views/compareSideBySide/GenericCompareSideBySidePage.astro
website/src/components/views/compareToBaseline/GenericCompareToBaselinePage.astro
website/src/components/views/compareVariants/GenericCompareVariantsPage.astro
website/src/pages/covid/compare-to-baseline.astro
website/src/pages/covid/compare-variants.astro
website/src/pages/flu/h5n1/compare-side-by-side.astro
website/src/pages/flu/h5n1/compare-to-baseline.astro
website/src/pages/flu/h5n1/compare-variants.astro
website/src/pages/flu/h5n1/single-variant.astro
website/src/pages/rsv-a/compare-side-by-side.astro
website/src/pages/rsv-a/compare-to-baseline.astro
website/src/pages/rsv-a/compare-variants.astro
website/src/pages/rsv-a/sequencing-efforts.astro
website/src/pages/rsv-a/single-variant.astro
website/src/pages/rsv-b/compare-side-by-side.astro
website/src/pages/rsv-b/compare-to-baseline.astro
website/src/pages/rsv-b/compare-variants.astro
website/src/pages/rsv-b/sequencing-efforts.astro
website/src/pages/rsv-b/single-variant.astro
website/src/pages/west-nile/compare-side-by-side.astro
website/src/pages/west-nile/compare-to-baseline.astro
website/src/pages/west-nile/compare-variants.astro
website/src/pages/west-nile/single-variant.astro

refactor(website): only pass organism - let the generic view page pick the view key

---

backend/src/main/resources/application-dashboards-dev.yaml
backend/src/main/resources/application-dashboards-prod.yaml
backend/src/main/resources/application-dashboards-staging.yaml

fix(website): west nile: change `mainDateField` to `sampleCollectionDateRangeLower`

---

backend/src/main/resources/application-dashboards-staging.yaml

fix(website): west nile: properly change `mainDateField` to `sampleCollectionDateRangeLower` for staging

---

website/src/components/auth/LoginButton.tsx

Fixes the login button to work again.

Fix login button

---

website/src/components/ErrorReportInstruction.tsx
website/src/components/subscriptions/create/SubscriptionsCreate.tsx
website/src/components/subscriptions/overview/SubscriptionEntry.tsx
website/src/components/views/analyzeSingleVariant/CollectionsList.tsx
website/src/styles/containers/Modal.tsx
website/src/styles/containers/ModalBox.tsx

Preparation for https://github.com/GenSpectrum/dashboards/issues/436 - at least we can see the error now.

fix(website): show error when parsing the collection variant filter fails

---

website/src/components/views/analyzeSingleVariant/CollectionsList.tsx

fix(website): don't crash when a collection variant doesn't have mutations

---

website/src/components/ErrorReportInstruction.tsx

fix(website): copy error to clipboard button

---

website/CONTRIBUTING.md

This is a starting point of a contributing readme. Feel free to add or remove points.

docs(website): add contributing docs

---

website/src/util/formatUrl.ts
website/src/views/covid.ts
website/src/views/pageStateHandlers/CompareSideBySidePageStateHandler.ts
website/src/views/pageStateHandlers/CompareToBaselinePageStateHandler.spec.ts
website/src/views/pageStateHandlers/CompareToBaselinePageStateHandler.ts
website/src/views/pageStateHandlers/CompareVariantsPageStateHandler.spec.ts
website/src/views/pageStateHandlers/CompareVariantsPageStateHandler.ts
website/src/views/pageStateHandlers/SequencingEffortsPageStateHandler.ts
website/src/views/pageStateHandlers/SingleVariantPageStateHandler.ts

Resolves: #454
Appends always a "&" sign to the url. Also cleans up the url, that empty url search params don't add a "?".

feat(website): end URL with & sign

---

website/src/components/views/sequencingEfforts/GenericSequencingEffortsPage.astro
website/src/views/locationHelpers.spec.ts
website/src/views/locationHelpers.ts

fix(website): title of sequences by location component on sequencing efforts pages

---

website/package-lock.json
website/package.json
website/src/components/genspectrum/GsMutations.astro
website/src/components/views/analyzeSingleVariant/GenericAnalyzeSingleVariantPage.astro
website/src/components/views/compareSideBySide/GenericCompareSideBySidePage.astro
website/src/pages/covid/compare-side-by-side.astro
website/src/pages/covid/single-variant.astro

related to https://github.com/GenSpectrum/dashboard-components/issues/608
Adding it to the compare side-by-side view:
and to the single variant view:

feat(website): add Jaccard similarity to gs-mutations table

---

website/src/components/views/sequencingEfforts/GenericSequencingEffortsPage.astro

fix(website): add header to number of sequences diagram table view

---

website/src/layouts/base/header/getPathogenMegaMenuSections.ts
website/src/pages/index.astro

I'll most likely need this in #299.

refactor(website): use a common source for both organism menus

---

website/package-lock.json
website/package.json
website/src/components/genspectrum/GsLineageFilter.tsx
website/src/components/genspectrum/GsTextInput.tsx
website/src/components/pageStateSelectors/LineageFilterInput.tsx

chore(website): update @genspectrum/dashboard-components to 0.13.0

---

website/src/components/InfluenzaWastewaterInfo.astro
website/src/components/genspectrum/GsWastewaterMutationsOverTime.astro
website/src/pages/swiss-wastewater/flu.astro
website/tests/CompareVariantsPage.ts

use an Astro slot instead of `set:html`

---

website/src/components/RsvWastewaterInfo.astro
website/src/pages/swiss-wastewater/rsv.astro
website/src/types/wastewaterConfig.ts

feat(website): add rsv info to wastewater mutations over time

---

LICENSE

I noticed that we don't have a license file for this repo and added one.

chore: add license (AGPL-3.0)

---

README.md
website/CONTRIBUTING.md

Some random docs improvements while studying the code.

Some docs improvements

---

backend/src/main/resources/application-dashboards-prod.yaml
backend/src/main/resources/application-dashboards-staging.yaml

feat(website): include data use terms in downloaded files of Pathoplexus organisms

---

website/README.md

Two details to help users succeed.

Small README additions

---

.commitlintrc.js
website/package-lock.json
website/package.json
website/src/components/genspectrum/GsDateRangeFilter.tsx
website/src/components/genspectrum/GsTextFilter.tsx
website/src/components/pageStateSelectors/BaselineSelector.tsx
website/src/components/pageStateSelectors/LineageFilterInput.tsx
website/tests/ViewPage.ts

Updates the code to the change in https://github.com/GenSpectrum/dashboard-components/issues/709

Rename to filter

---

website/src/components/RsvWastewaterInfo.astro
website/src/pages/swiss-wastewater/rsv.astro

feat(website): add info for RSV aa mutations (soon to be added)

---

website/src/views/mpox.ts
website/src/views/westNile.ts

chore(website): make date range filter label less confusing for users

---

website/src/views/routing.ts

feat(website): change order of views

---

backend/src/main/resources/application-dashboards-prod.yaml
backend/src/main/resources/application-dashboards-staging.yaml
website/src/pages/ebola-sudan/compare-side-by-side.astro
website/src/pages/ebola-sudan/compare-to-baseline.astro
website/src/pages/ebola-sudan/compare-variants.astro
website/src/pages/ebola-sudan/index.astro
website/src/pages/ebola-sudan/sequencing-efforts.astro
website/src/pages/ebola-sudan/single-variant.astro
website/src/types/Organism.ts
website/src/views/ebolaSudan.ts
website/src/views/routing.ts
website/tests/compareVariants.spec.ts
website/tests/sequencingEfforts.spec.ts

feat(website): add Ebola Sudan dashboard

---

website/src/views/cchf.ts
website/src/views/ebolaSudan.ts
website/src/views/ebolaZaire.ts

because "last year" shows no data

feat(website): change default date range to all times for Ebola and CCHF

---

website/src/components/genspectrum/AdvancedQueryFilter.tsx
website/src/components/genspectrum/GsMutationFilter.tsx
website/src/components/pageStateSelectors/LineageFilterInput.tsx

Without labels, it can be unclear what the entry is about, and for consistency with the other entries.

feat(website): add labels to variant filter inputs

---

backend/src/main/kotlin/org/genspectrum/dashboardsbackend/config/DashboardsConfig.kt
backend/src/main/resources/application-dashboards-prod.yaml
backend/src/main/resources/application-dashboards-staging.yaml
backend/src/test/resources/application.yaml
website/src/config.ts
website/src/views/cchf.ts
website/src/views/covid.ts
website/src/views/ebolaSudan.ts
website/src/views/ebolaZaire.ts
website/src/views/flu.ts
website/src/views/h5n1.ts
website/src/views/mpox.ts
website/src/views/rsvA.ts
website/src/views/rsvB.ts
website/src/views/westNile.ts

feat(website): add host as a filter option

---

website/src/components/pageStateSelectors/CompareSideBySidePageStateSelector.tsx

Resolves: #625
Bug was introduced in the update to tailwind 4.

fix(website): fill available space for filter on side-by-side view

---

website/src/layouts/Breadcrumbs.tsx
website/src/layouts/base/header/getPathogenMegaMenuSections.ts
website/src/pages/swiss-wastewater/flu.astro
website/src/pages/swiss-wastewater/rsv.astro
website/src/types/wastewaterConfig.ts

fix(website): make all breadcrumb items a link

---

website/src/views/OrganismConstants.ts
website/src/views/cchf.ts
website/src/views/covid.ts
website/src/views/ebolaSudan.ts
website/src/views/ebolaZaire.ts
website/src/views/h1n1pdm.ts
website/src/views/h3n2.ts
website/src/views/h5n1.ts
website/src/views/influenza-a.ts
website/src/views/influenza-b.ts
website/src/views/mpox.ts
website/src/views/rsvA.ts
website/src/views/rsvB.ts
website/src/views/victoria.ts
website/src/views/westNile.ts
website/tests/ViewPage.ts

Resolves #550
Adds more filters to each view. 
Leftover: completeness. New ticket: #637

feat(website): add more filter fields

---

website/package-lock.json
website/package.json

resolves #
I installed using `npm install @genspectrum/dashboard-components@0.18.3` - is this not the correct way?

feat(website): update dashboard components to 0.18.4

---

website/src/util/defaultDateRangeOption.ts
website/src/views/cchf.ts
website/src/views/covid.ts
website/src/views/ebolaSudan.ts
website/src/views/ebolaZaire.ts
website/src/views/h1n1pdm.ts
website/src/views/h3n2.ts
website/src/views/h5n1.ts
website/src/views/influenza-a.ts
website/src/views/influenza-b.ts
website/src/views/mpox.ts
website/src/views/rsvA.ts
website/src/views/rsvB.ts
website/src/views/victoria.ts
website/src/views/westNile.ts

refactor(website): extract reoccuring date range options

---

.commitlintrc.js

chore: disable commitlint check for footer length

---

backend/src/main/resources/application-dashboards-prod.yaml
backend/src/main/resources/application-dashboards-staging.yaml
website/src/config.ts
website/src/layouts/base/header/getPathogenMegaMenuSections.ts
website/src/pages/swiss-wastewater/flu.astro
website/src/pages/swiss-wastewater/rsv.astro
website/src/types/wastewaterConfig.ts
website/src/views/ViewConstants.ts

feat(website): add description to external links on organism index page

---

website/package-lock.json
website/package.json
website/src/components/subscriptions/create/SubscriptionsCreate.tsx
website/src/layouts/base/BaseLayout.astro
website/vitest.config.js

chore(website): update @genspectrum/dashboard-components to 0.19.0

---

website/src/components/ComponentHeadline.astro
website/src/components/ComponentWrapper.astro
website/src/components/genspectrum/GsWastewaterMutationsOverTime.astro
website/src/pages/swiss-wastewater/flu.astro
website/src/pages/swiss-wastewater/rsv.astro

resolves https://github.com/GenSpectrum/dashboards/issues/649

feat(website): make nucleotide mutations section expandable for WISE

---

backend/src/main/resources/application-dashboards-staging.yaml

chore(website): use staging LAPIS for Covid data on staging

---

website/src/pages/data.astro

feat(website): mention Ebola reference sequences on data sources page

---

website/README.md

resolves #
As I forgot the state and these steps do not appear to be in this repo I thought I would add them here (please correct me if there are indeed docs in this repo)

chore(docs): update docs to have deployment steps

---

website/src/views/pageStateHandlers/dateFilterFromToUrl.spec.ts
website/src/views/pageStateHandlers/dateFilterFromToUrl.ts

fix(website): correctly deserialize undefined date ranges from url

---

website/src/views/denv1.ts
website/src/views/denv2.ts
website/src/views/denv3.ts
website/src/views/denv4.ts
website/src/views/mpox.ts
website/src/views/rsvA.ts
website/src/views/rsvB.ts

resolves #749
- ~[ ] All necessary documentation has been adapted.~
- ~[ ] The implemented feature is covered by an appropriate test.~

feat(website): use sublineages for denv, mpox and rsv

---

website/src/components/views/analyzeSingleVariant/GenericAnalyzeSingleVariantPage.astro
website/src/pages/covid/single-variant.astro

resolves #745
~~- [ ] All necessary documentation has been adapted.~~
~~- [ ] The implemented feature is covered by an appropriate test.~~

fix(website): add download button to single variants page even when no variant is selected

---

website/tests/compareVariants.spec.ts
website/tests/mainPage.spec.ts
website/tests/sequencingEfforts.spec.ts

~~- [ ] All necessary documentation has been adapted.~~
~~- [ ] The implemented feature is covered by an appropriate test.~~

test(website): temporarily disable denv2 e2e tests as LAPIS currently doesn't have data
