GenSpectrum/dashboards

backend/src/test/kotlin/org/genspectrum/dashboardsbackend/SwaggerUiTest.kt, website/src/auth.config.mjs, website/src/config.ts, website/src/env.d.ts, website/src/pages/api/subscriptions/[...path].ts, website/tests/config/dashboards_config.example.json
resolves #75
This adds outh2 authentification to the backend. We use the same cookies we produce on the website. It is currently not possible to add the auth to swagger. This will be done in #116
=> feat(backend): add oauth2 for all endpoints #75

backend/src/main/kotlin/org/genspectrum/dashboardsbackend/controller/SubscriptionsController.kt, backend/src/main/kotlin/org/genspectrum/dashboardsbackend/model/SubscriptionModel.kt, backend/src/main/kotlin/org/genspectrum/dashboardsbackend/subscriptions/Subscription.kt, backend/src/test/kotlin/org/genspectrum/dashboardsbackend/controller/SubscriptionsClient.kt, backend/src/test/kotlin/org/genspectrum/dashboardsbackend/controller/SubscriptionsControllerTest.kt
resolves #79
Adds the endpoint PUT '/subscriptions/{id}', which lets users edit an existing subscription.
=> feat(backend): add put endpoint to update a subscription by its id #79

backend/src/main/kotlin/org/genspectrum/dashboardsbackend/api/TriggerEvaluation.kt, backend/src/main/kotlin/org/genspectrum/dashboardsbackend/model/triggerevaluation/TriggerEvaluator.kt, backend/src/test/kotlin/org/genspectrum/dashboardsbackend/model/triggerevaluation/ProportionTriggerEvaluatorTest.kt
=> feat(backend): for now, evaluate "denominator = 0"-proportion triggers to "condition not met"

website/src/components/subscriptions/overview/SubscriptionEntry.tsx
resolves #207
When clicking the delete subscription button, the user is now shown a modal. The modal can be closed by clicking outside, pressing the escape button, or by clicking the discard button. When clicking the delete button the subscription is deleted. 
The user can also use the tab button to go through the selection. When pressing enter the selected action is performed.
=> feat(website): confirm deletion of subscription #207

website/src/layouts/base/header/MegaMenu.tsx, website/src/layouts/base/header/Navigation.tsx, website/src/pages/index.astro
resolves #
Using https://icon-sets.iconify.design/mdi/external-link/ to make it more obvious that you will leave the page when clicking the CovSpectrum link.
=> feat(website): mark external navigation links

website/src/layouts/OrganismPage/OrganismPageLayout.astro, website/src/layouts/base/BaseLayout.astro, website/src/layouts/base/Footer.astro, website/src/layouts/base/footer/DataInfo.astro, website/src/layouts/base/footer/DataOriginLink.astro, website/src/layouts/base/footer/Footer.astro, website/src/layouts/base/footer/FooterNavigation.astro, website/src/layouts/base/footer/PrimaryFooter.astro, website/src/layouts/base/footer/SecondaryFooter.astro, website/src/pages/index.astro, website/src/types/dataOrigins.ts, website/src/views/covid.ts, website/src/views/h5n1.ts, website/src/views/mpox.ts, website/src/views/rsvA.ts, website/src/views/rsvB.ts, website/src/views/westNile.ts
resolves #234 
resolves #225
This PR changes the design of the footer. There is now a primary footer, which should be shown on every page. It is vertically centered, and a secondary footer with additional information for each single page. For now this only holds the origin of the data. 
The footer is now positioned always at the bottom of the page.
On home page
On organism page
On subscription page
=> 234 show pathogen specific data source footer

website/src/components/subscriptions/overview/SubscriptionDisplay.tsx, website/src/util/proportionAsPercent.ts
resolves https://github.com/GenSpectrum/dashboards/issues/211
Round to precision 3 decimal points:
otherwise for evaluated values below threshold: 
keep integers as they are:
=> feat(website): round trigger evaluation results (#211)

backend/src/main/resources/application-dashboards-dev.yaml, backend/src/main/resources/application-dashboards-prod.yaml, backend/src/main/resources/application-dashboards-staging.yaml
The RSV instances seem to have no lineage field yet... We will need to fix that in the deployment.
=> fix: config after changing the DNS entry for lapis.genspectrum.org from s1 to prod

website/src/config.ts, website/src/layouts/base/header/CallToAction.astro
resolves #283
The environment variable `DASHBOARDS_ENVIRONMENT` now toggles also, if the login button should be shown or not. We remove this condition, once we have the subscription feature ready.
The button no longer shows on prod. The layout is the same as before.
=> feat(website): hide login button on prod

website/src/components/genspectrum/GsMutationFilter.tsx
resolves #
In https://github.com/GenSpectrum/dashboard-components/pull/511 we removed the blur dispatch event from the mutation filter component, this PR reflects this change in genspectrum dashboards. 
The dispatch event was unused and was not accurate (e.g. it did not fire if a user moved outside of the component if they moved outside after deleting mutations)
=> feat(website): remove unused onBlur value from GsMutationFilter as removed in https://github.com/GenSpectrum/dashboard-components/pull/511

website/patches/auth-astro+4.1.3.patch, website/src/components/auth/LoginButton.astro
A copy of #322 to be merged into main instead of into another PR.
The dependency is not installed transitively - we don't want to install it ourselves We have to satisfy Typescript and the linter here. I originally fixed the build with auth-astro in #307, but this seems a better fix, since it simply removes the imports from the missing dependency.
=> chore(website): patch auth-astro - manually import types from next-auth/react

website/src/views/BaseView.ts, website/src/views/View.ts, website/src/views/covid.ts, website/src/views/h5n1.ts, website/src/views/rsvA.ts, website/src/views/rsvB.ts, website/src/views/westNile.ts
resolves #
The built website would crash with "ReferenceError: can't access lexical declaration '$e' before initialization" (in Firefox) $e was one of the abstract view classes.
I guess this was due to a cyclic dependency (view requiring state handlers requiring view), but I'm not 100% sure. It works with the abstract view classes extracted to a separate file though.
=> fix(website): fix reference error in built artifact

website/src/components/ErrorReportInstruction.tsx, website/src/components/subscriptions/backendApi/backendService.spec.ts, website/src/components/subscriptions/backendApi/backendService.ts, website/src/components/subscriptions/create/SubscriptionsCreate.tsx, website/src/components/subscriptions/overview/SubscriptionEntry.tsx, website/src/pages/500.astro, website/src/pages/api/subscriptions/[...path].ts, website/src/views/PageStateHandler.ts
resolves #256
On client side (where the error can be seen in console and network tab anyway): Now shows the error message 
* in the error information that's supposed to be copied to our GitHub issues
* in the error toast, if it should be user facing
On server side: Shows the error message
* in the error information,  if it should be user facing
* in the error toast, if it should be user facing
=> feat(website): show more useful error messages to the user

website/src/components/GenericCompareSideBySidePage.astro
=> feat(website): remove relative growth advantage chart from non-covid side-by-side views

.github/workflows/rebaseProd.yml
resolves #360
I tested this on a private repo. This would require allowing GitHub actions to create/approve PRs (Settings > Actions > General):
@chaoran-chen would it be ok if you enable this setting? Also it's probably good to add some branch protection rules for `prod` (at least restrict deletion and force pushes - maybe also add that it requires a PR to update, if we decide to keep this action).
=> build: add workflow that creates a PR to update the prod branch

backend/src/main/kotlin/org/genspectrum/dashboardsbackend/config/DashboardsConfig.kt
IntelliJ warned:
"Property with 'Array' type in a 'data' class: it is recommended to override 'equals()' and 'hashCode()'" This is the easiest way to get rid of that warning.
=> chore(backend): use List instead of Array

website/src/components/GenericCompareVariantsPage.astro, website/src/components/pageStateSelectors/ApplyFilterButton.tsx, website/src/components/pageStateSelectors/CompareSideBySidePageStateSelector.tsx, website/src/components/pageStateSelectors/CompareVariantsPageStateSelector.tsx, website/src/components/pageStateSelectors/SequencingEffortsPageStateSelector.tsx, website/src/components/pageStateSelectors/SingleVariantPageStateSelector.tsx, website/src/components/rsv/RsvSequencingEffortsPage.astro, website/src/components/views/analyzeSingleVariant/GenericAnalyzeSingleVariantPage.astro, website/src/pages/covid/sequencing-efforts.astro, website/src/pages/covid/single-variant.astro, website/src/pages/flu/h5n1/sequencing-efforts.astro, website/src/pages/west-nile/sequencing-efforts.astro
So that the browser displays a preview where it's going when hovering it. And previously the button was essentially a link, because onChange just set `window.location.href`. We can let the `<a>` tag do that.
=> refactor(website): make the "Apply filters" button a link

website/src/components/pageStateSelectors/CompareVariantsPageStateSelector.tsx, website/src/components/pageStateSelectors/CompareVariantsToBaselineStateSelector.tsx, website/src/components/pageStateSelectors/FallbackElement.tsx, website/src/components/pageStateSelectors/SequencingEffortsPageStateSelector.tsx, website/src/components/pageStateSelectors/SingleVariantPageStateSelector.tsx, website/src/components/rsv/RsvSequencingEffortsPage.astro, website/src/components/views/analyzeSingleVariant/GenericAnalyzeSingleVariantPage.astro, website/src/components/views/compareSideBySide/GenericCompareSideBySidePage.astro, website/src/components/views/compareToBaseline/GenericCompareToBaselinePage.astro, website/src/components/views/compareVariants/GenericCompareVariantsPage.astro, website/src/layouts/OrganismPage/SingleVariantOrganismPageLayout.astro, website/src/pages/covid/compare-side-by-side.astro, website/src/pages/covid/sequencing-efforts.astro, website/src/pages/covid/single-variant.astro, website/src/pages/flu/h5n1/sequencing-efforts.astro, website/src/pages/west-nile/sequencing-efforts.astro
Resolves #363
Adds a fallback to our client-side loaded PageStateSelectors. The page now show not shift anylonger. 
Know issues:
- the mutation filter expands when there are mutations selected. It is hard to compensate for that
- the covid collections are of different size. They therefore shift the other elements. However, on the analyze single variant page, this does not show so prominent, since the filter covers almost the whole screen on mobile.
While loading:
When finished loading:
=> feat(website): add fallback element for filters

backend/src/main/resources/application-dashboards-dev.yaml, backend/src/main/resources/application-dashboards-prod.yaml, backend/src/main/resources/application-dashboards-staging.yaml, website/src/pages/covid/index.astro, website/src/pages/data.astro, website/src/pages/flu/h5n1/index.astro, website/src/pages/mpox/compare-side-by-side.astro, website/src/pages/mpox/compare-to-baseline.astro, website/src/pages/mpox/compare-variants.astro, website/src/pages/mpox/index.astro, website/src/pages/mpox/sequencing-efforts.astro, website/src/pages/mpox/single-variant.astro, website/src/pages/rsv-a/index.astro, website/src/pages/rsv-b/index.astro, website/src/pages/west-nile/index.astro, website/src/types/Organism.ts, website/src/views/covid.ts, website/src/views/h5n1.ts, website/src/views/mpox.ts, website/src/views/routing.ts, website/src/views/rsvB.ts, website/src/views/westNile.ts, website/tests/compareVariants.spec.ts, website/tests/mainPage.spec.ts
Resolves: #395
Adds Mpox back to the list of organisms, with all views. Now uses the same sequencing efforts page as west-nile.
=> 395 bring back mpox pages

website/src/layouts/base/header/MegaMenu.tsx, website/src/views/ViewConstants.ts, website/tests/mainPage.spec.ts
Resolves: #402
Now allows for a scrollable mega menu. Also adjust the columns of the mega menu.
Three column menu
Two column menu
=> fix(website): allow scrolling on mega menu

website/src/pages/covid/single-variant.astro
Otherwise, the component will show an error on the single variant page of covid.
=> fix(website): add required lapisDateField to relative growth advantage

website/.prettierrc, website/src/components/views/analyzeSingleVariant/GenericAnalyzeSingleVariantPage.astro, website/src/components/views/compareSideBySide/GenericCompareSideBySidePage.astro, website/src/components/views/compareToBaseline/GenericCompareToBaselinePage.astro, website/src/components/views/compareVariants/GenericCompareVariantsPage.astro, website/src/components/views/sequencingEfforts/GenericSequencingEffortsPage.astro, website/src/views/routing.ts
resolves #
Currently the generic view pages will error if an organism does not have that page - as the pages an organism has should be customizable we create a new organism subtype which includes all organisms with that specific view/page. 
Thanks @chaoran-chen for helping with this!
=> feat(website): Allow each organism to not include all pages

website/src/components/views/compareToBaseline/GenericCompareToBaselinePage.astro, website/src/components/views/compareToBaseline/SelectBaseline.astro, website/tests/mainPage.spec.ts, website/tests/sequencingEfforts.spec.ts
resolves https://github.com/GenSpectrum/dashboards/issues/421
Since the refactor a landing page is required for the compare baseline page - this PR adds a landing page with a description of the component to be shown when no variants are selected.
It additionally adds an e2e test to ensure no component can have an error on a page on first load. Confirmed this fails on the main page currently:
=> feat(website): add compare to baseline landing page

website/src/components/pageStateSelectors/SequencingEffortsPageStateSelector.tsx, website/src/components/pageStateSelectors/VariantSelector.tsx, website/src/components/views/analyzeSingleVariant/CollectionsList.tsx, website/src/components/views/compareSideBySide/GenericCompareSideBySidePage.astro, website/src/components/views/sequencingEfforts/GenericSequencingEffortsPage.astro, website/src/views/BaseView.ts, website/src/views/OrganismConstants.ts, website/src/views/covid.ts, website/src/views/h5n1.ts, website/src/views/mpox.ts, website/src/views/pageStateHandlers/CompareSideBySidePageStateHandler.ts, website/src/views/pageStateHandlers/CompareToBaselinePageStateHandler.spec.ts, website/src/views/pageStateHandlers/CompareToBaselinePageStateHandler.ts, website/src/views/pageStateHandlers/CompareVariantsPageStateHandler.spec.ts, website/src/views/pageStateHandlers/CompareVariantsPageStateHandler.ts, website/src/views/pageStateHandlers/PageStateHandler.ts, website/src/views/pageStateHandlers/SequencingEffortsPageStateHandler.ts, website/src/views/pageStateHandlers/SingleVariantPageStateHandler.ts, website/src/views/rsvA.ts, website/src/views/rsvB.ts, website/src/views/westNile.ts
This will be very useful for influenza - but its anyways nice to give users more filter options - this also gives the option to not show sequence mutations on the compare variant page - which will also be useful for Influenza and other parent pages where we group all information and do not align. 
resolves #
https://github.com/user-attachments/assets/04ed1a51-3c95-426a-82b2-004ff4f7fbc9
=> feat(website): add option to search by clades on sequencing efforts page

website/src/components/ComponentHeadline.astro, website/src/components/ComponentWrapper.astro, website/src/components/genspectrum/GsStatistics.astro, website/src/components/views/analyzeSingleVariant/GenericAnalyzeSingleVariantPage.astro, website/src/layouts/base/BaseLayout.astro, website/src/layouts/base/header/headerConstants.ts, website/src/pages/covid/single-variant.astro
resolves #426
Clicking the headline will scroll to the component. When hovering the headline, a link symbol is displayed.
=> feat(website): add fragment links to scroll to component headlines

website/src/components/genspectrum/GsAggregate.astro
To prepare for https://github.com/GenSpectrum/dashboard-components/pull/639. Otherwise, we will have unexpected bar charts.
=> fix(website): explicitly specify views on `gs-aggregate`

website/src/components/genspectrum/GsWastewaterMutationsOverTime.astro, website/src/pages/swiss-wastewater/flu.astro
resolves #
This requires https://github.com/GenSpectrum/dashboard-components/pull/686
As requested prior to the launch tomorrow we need to add info to the dashboards - this adds info for influenza - sadly the links do not show as links as this has to be passed to the dashboard components
=> feat(website): WISE dashboard - add influenza specific info

website/package-lock.json, website/package.json
This is breaking due to the changed default of the `height` attribute. We always set the height, so it doesn't affect us.
=> chore(website): update components to 0.16

website/src/components/genspectrum/GsAggregate.astro, website/src/components/views/analyzeSingleVariant/GenericAnalyzeSingleVariantPage.astro, website/src/components/views/compareSideBySide/GenericCompareSideBySidePage.astro, website/src/components/views/sequencingEfforts/GenericSequencingEffortsPage.astro, website/src/pages/covid/compare-side-by-side.astro, website/src/pages/covid/single-variant.astro, website/src/views/OrganismConstants.ts, website/src/views/covid.ts
resolves #476 
- add some return type definitions (useful for catching the missing fields for the other changes)
- GsAggregate astro component: require a `views` argument.
- Add `views` field to `additionalSequencingEffortsFields`, to enable
configuration per such entry.
- Add the `views` argument statically to the remaining GsAggregate
call sites.
=> use aggregates bar chart

website/src/components/ComponentWrapper.astro, website/src/components/genspectrum/GsAggregate.astro, website/src/components/genspectrum/GsMutationComparison.astro, website/src/components/genspectrum/GsMutations.astro, website/src/components/genspectrum/GsMutationsOverTime.astro, website/src/components/genspectrum/GsNumberSequencesOverTime.astro, website/src/components/genspectrum/GsPrevalenceOverTime.astro, website/src/components/genspectrum/GsRelativeGrowthAdvantage.astro, website/src/components/genspectrum/GsSequencesByLocation.astro, website/src/components/views/analyzeSingleVariant/GenericAnalyzeSingleVariantPage.astro, website/src/components/views/compareSideBySide/GenericCompareSideBySidePage.astro, website/src/components/views/compareToBaseline/GenericCompareToBaselinePage.astro, website/src/components/views/compareVariants/GenericCompareVariantsPage.astro, website/src/components/views/sequencingEfforts/GenericSequencingEffortsPage.astro, website/src/pages/covid/compare-side-by-side.astro, website/src/pages/covid/single-variant.astro, website/src/views/OrganismConstants.ts, website/src/views/covid.ts
Resolves #567
Resolves #566
Uses the new auto height feature for tables and mutations over time component. 
As discussed: We have still some whitespace below the tables, when there are too few entries (see also screenshot). We could try to use two columns instead of the grid. However, this would undermine the horizontal aligments of the tables. Therefore we keep it like this.
=> feat(website): use auto height for tables and mutation over time

website/src/views/BaseView.ts, website/src/views/OrganismConstants.ts, website/src/views/cchf.ts, website/src/views/covid.ts, website/src/views/ebolaSudan.ts, website/src/views/ebolaZaire.ts, website/src/views/flu.ts, website/src/views/h5n1.ts, website/src/views/mpox.ts, website/src/views/pageStateHandlers/CompareSideBySidePageStateHandler.spec.ts, website/src/views/pageStateHandlers/CompareSideBySidePageStateHandler.ts, website/src/views/pageStateHandlers/CompareToBaselinePageStateHandler.spec.ts, website/src/views/pageStateHandlers/CompareToBaselinePageStateHandler.ts, website/src/views/pageStateHandlers/CompareVariantsPageStateHandler.spec.ts, website/src/views/pageStateHandlers/CompareVariantsPageStateHandler.ts, website/src/views/pageStateHandlers/SequencingEffortsPageStateHandler.ts, website/src/views/pageStateHandlers/SingleVariantPageStateHandler.spec.ts, website/src/views/pageStateHandlers/SingleVariantPageStateHandler.ts, website/src/views/rsvA.ts, website/src/views/rsvB.ts, website/src/views/westNile.ts
The original idea was to only have a minimal set of value in OrganismConstants and extend when necessary. Reality showed that we never use a minimal set, but always the full set instead. The separation became irrelevant, so let's remove it.
=> refactor(website): merge ExtendedConstants into OrganismConstants

website/eslint.config.js, website/package-lock.json, website/package.json, website/src/components/pageStateSelectors/CompareSideBySidePageStateSelector.tsx, website/src/components/pageStateSelectors/CompareVariantsPageStateSelector.tsx, website/src/components/pageStateSelectors/CompareVariantsToBaselineStateSelector.tsx, website/src/components/pageStateSelectors/SequencingEffortsPageStateSelector.tsx, website/src/components/pageStateSelectors/SingleVariantPageStateSelector.tsx
We discovered in https://github.com/GenSpectrum/dashboards/pull/600#discussion_r1977137244 that apparently the plugin wasn't included properly so that we didn't get the linter errors.
=> chore(website): fix usage of eslint-plugin-react-hooks plugin

website/src/pages/covid/single-variant.astro, website/src/views/covid.ts
The reason to implement it using a separate component instantiation rather than adding another `LineageFilterConfig` to `CovidConstants.lineageFilters` (which adds another column to the existing output) is that the ~corresponding Nextstrain Clade for a Nextclade pango lineage is not actually associated with the same data, thus it would be wrong. Also, the bar chart currently only shows the first column, thus would not show the Nextstrain Clade names.
resolves #559
=> feat(website): add 'Sub-lineages Neststrain Clade' for Sars-Cov-2

website/src/components/views/overview/GenericOverview.astro, website/src/layouts/base/header/HamburgerMenu.astro, website/src/layouts/base/header/MegaMenu.tsx, website/src/layouts/base/header/Navigation.tsx, website/src/layouts/base/header/getPathogenMegaMenuSections.ts, website/src/pages/cchf/index.astro, website/src/pages/covid/index.astro, website/src/pages/ebola-sudan/index.astro, website/src/pages/ebola-zaire/index.astro, website/src/pages/flu/h5n1/index.astro, website/src/pages/flu/index.astro, website/src/pages/index.astro, website/src/pages/mpox/index.astro, website/src/pages/rsv-a/index.astro, website/src/pages/rsv-b/index.astro, website/src/pages/swiss-wastewater/index.astro, website/src/pages/west-nile/index.astro, website/src/styles/containers/PageContainer.tsx, website/src/views/BaseView.ts, website/src/views/ViewConstants.ts
resolves #622 
- adds an index page for each organism
- it can be navigated to this page, through clicking on the breadcrumb menu, on the organism on the main page and on the organism in the menu
The design very basic and can be improved, but this task will be adressed by antoher issue and might also be part of #619
=> Add index page for each organism and wastewater

website/src/components/genspectrum/GsDateRangeFilter.tsx, website/src/components/pageStateSelectors/BaselineSelector.tsx, website/src/util/chooseGranularityBasedOnDateRange.spec.ts, website/src/util/chooseGranularityBasedOnDateRange.ts, website/src/views/BaseView.ts, website/src/views/View.ts, website/src/views/cchf.ts, website/src/views/covid.ts, website/src/views/ebolaSudan.ts, website/src/views/ebolaZaire.ts, website/src/views/h1n1pdm.ts, website/src/views/h3n2.ts, website/src/views/h5n1.ts, website/src/views/influenza-a.ts, website/src/views/influenza-b.ts, website/src/views/mpox.ts, website/src/views/pageStateHandlers/CompareSideBySidePageStateHandler.spec.ts, website/src/views/pageStateHandlers/CompareToBaselinePageStateHandler.spec.ts, website/src/views/pageStateHandlers/CompareVariantsPageStateHandler.spec.ts, website/src/views/pageStateHandlers/PageStateHandler.ts, website/src/views/pageStateHandlers/SingleVariantPageStateHandler.spec.ts, website/src/views/rsvA.ts, website/src/views/rsvB.ts, website/src/views/victoria.ts, website/src/views/westNile.ts
resolves #617
When the user clicks the "x" button to delete the current input of a date range filter, then it will send an event with `event.detail = null`. Correctly handle that and make sure that we don't store those in the URL.
=> fix(website): correctly handle deleting the value of a date range filter

backend/src/main/kotlin/org/genspectrum/dashboardsbackend/config/DashboardsConfig.kt, backend/src/main/resources/application-dashboards-prod.yaml, backend/src/main/resources/application-dashboards-staging.yaml, backend/src/test/resources/application.yaml, website/src/config.ts, website/src/views/OrganismConstants.ts, website/src/views/cchf.ts, website/src/views/covid.ts, website/src/views/ebolaSudan.ts, website/src/views/ebolaZaire.ts, website/src/views/h1n1pdm.ts, website/src/views/h3n2.ts, website/src/views/h5n1.ts, website/src/views/influenza-a.ts, website/src/views/influenza-b.ts, website/src/views/mpox.ts, website/src/views/rsvA.ts, website/src/views/rsvB.ts, website/src/views/victoria.ts, website/src/views/westNile.ts, website/vitest.setup.ts
resolves #593
We only need values in the config that both website and backend need to access.
=> refactor(website): move values from the config to the organism constants

website/src/components/views/analyzeSingleVariant/GenericAnalyzeSingleVariantPage.astro, website/src/components/views/compareSideBySide/GenericCompareSideBySidePage.astro, website/src/components/views/sequencingEfforts/GenericSequencingEffortsPage.astro, website/src/pages/covid/compare-side-by-side.astro, website/src/pages/covid/single-variant.astro, website/src/views/OrganismConstants.ts, website/src/views/cchf.ts, website/src/views/covid.ts, website/src/views/ebolaSudan.ts, website/src/views/ebolaZaire.ts, website/src/views/h1n1pdm.ts, website/src/views/h3n2.ts, website/src/views/h5n1.ts, website/src/views/influenza-a.ts, website/src/views/influenza-b.ts, website/src/views/mpox.ts, website/src/views/pageStateHandlers/CompareSideBySidePageStateHandler.spec.ts, website/src/views/pageStateHandlers/CompareToBaselinePageStateHandler.spec.ts, website/src/views/pageStateHandlers/CompareVariantsPageStateHandler.spec.ts, website/src/views/pageStateHandlers/SingleVariantPageStateHandler.spec.ts, website/src/views/rsvA.ts, website/src/views/rsvB.ts, website/src/views/victoria.ts, website/src/views/westNile.ts
resolves #636
This is mostly a refactoring to make it configurable. The idea was to include all `gs-aggregated`s into the `additionalSequencingEffortsFields` (which are no longer "additional" then). Consequently, I introduced the same concept for the other views that use `gs-aggregated` in the same manner.
=> bar chart as default for sub lineages for influenza a sequencing efforts

website/src/components/genspectrum/GsDateRangeFilter.tsx, website/src/components/genspectrum/GsLineageFilter.tsx, website/src/components/genspectrum/GsLocationFilter.tsx, website/src/components/genspectrum/GsMutationFilter.tsx, website/src/components/genspectrum/GsTextFilter.tsx
Follow up to #686. We now use the constant of the filter names, instead of a string. Also changes, that there is an ealry return in the useEffect inside the filters
=> chore(website): use event name constants instead of string

docker-compose.yml, website/.env.e2e, website/.env.example, website/README.md, website/src/components/genspectrum/AdvancedQueryFilter.tsx, website/src/components/pageStateSelectors/BaselineSelector.tsx, website/src/components/pageStateSelectors/CompareSideBySidePageStateSelector.tsx, website/src/components/pageStateSelectors/CompareVariantsPageStateSelector.tsx, website/src/components/pageStateSelectors/CompareVariantsToBaselineStateSelector.tsx, website/src/components/pageStateSelectors/SequencingEffortsPageStateSelector.tsx, website/src/components/pageStateSelectors/SingleVariantPageStateSelector.spec.tsx, website/src/components/pageStateSelectors/SingleVariantPageStateSelector.tsx, website/src/components/pageStateSelectors/VariantSelector.tsx, website/src/components/pageStateSelectors/VariantsSelector.tsx, website/src/components/views/analyzeSingleVariant/GenericAnalyzeSingleVariantPage.astro, website/src/components/views/compareSideBySide/GenericCompareSideBySidePage.astro, website/src/components/views/compareToBaseline/GenericCompareToBaselinePage.astro, website/src/components/views/compareVariants/GenericCompareVariantsPage.astro, website/src/components/views/sequencingEfforts/GenericSequencingEffortsPage.astro, website/src/config.ts, website/src/env.d.ts, website/src/pages/covid/compare-side-by-side.astro, website/src/pages/covid/single-variant.astro
Follow up to #735:
import.meta.env.PUBLIC_DASHBOARDS_ENVIRONMENT is evaluated a build time, but we need to evaluate at runtime whether to show the AdvancedQueryFilter or not. Then we also don't need to have the env variable public.
~~- [ ] The implemented feature is covered by an appropriate test.~~
=> fix(website): evaluate env variable at runtime whether to show advanced query filter or not

website/src/components/genspectrum/GsMutationsOverTime.tsx
Expose the `displayMutations` setting on the MutationsOverTime component so we can set it inside of the dashboards.
=> feat(components): expose displayMutations parameter on mutationsOverTime component

website/src/components/views/wasap/WasapPage.tsx, website/src/util/Loading.tsx
Adds a `Loading` component which displays the spinner used in other places already.
(the loading component is only shown for a split second, before the plot component is then loaded, around 2 seconds into the video.)
https://github.com/user-attachments/assets/59cd71c4-f5a4-4dbc-9a5c-984de7962b4c
=> feat(website): add Loading component with spinner to the W-ASAP dashboard

website/src/components/views/wasap/WasapPage.tsx
Remove dependency array from `useMemo` that contained only a reference to a variable that wasn't part of the component.
=> chore(dashboards): fix linter warning

website/src/components/pageStateSelectors/WasapPageStateSelector.tsx
resolves #820 
Turns the 'granularity filter' into a generic radio component, and then reuses that for the sequence type selector.
=> feat(website): use a radio select for the sequence type filter

website/src/components/genspectrum/GsMutationFilter.tsx, website/src/components/pageStateSelectors/WasapPageStateSelector.tsx
resolves #808 
After it's now possible to restrict the mutation type input, we want only to be able to input _mutations_ (not insertions) and only Nuc or AA, depending on the selected sequence type. This has been implemented here.
https://github.com/user-attachments/assets/d02d1529-5ed9-4eb6-8bb7-76dddb77c8ba
=> feat(website): restrict mutation types on wastewater dashboard

website/src/components/pageStateSelectors/WasapPageStateSelector.tsx, website/src/components/views/wasap/WasapPage.tsx, website/src/views/pageStateHandlers/WasapPageStateHandler.ts
Refactors the `WasapFilter` into a `base` component and into 4 distinct `analysis` types.
In the PageStateSelector, I'm keeping track of all 4 analysis mode settings, so you can go back-and-forth between modes and not lose your settings.
Not sure whether it's better to add tests in the PR as well, or split into a new one. I think I'd be fine with merging as is, and treating testing as a new PR. To test the components, I think I might also do another refactoring and split things into sub-components that can be tested on their own.
n/a
=> refactor(website): stricter typing for WASAP filter

website/src/components/pageStateSelectors/DynamicDateFilter.browser.spec.tsx, website/src/components/pageStateSelectors/DynamicDateFilter.tsx, website/src/components/pageStateSelectors/WasapPageStateSelector.tsx, website/src/components/views/wasap/WasapPage.tsx, website/src/pages/swiss-wastewater/covid.astro, website/src/types/wastewaterConfig.ts, website/src/util/weeklyAndMonthlyDateRangeOption.spec.ts, website/src/util/weeklyAndMonthlyDateRangeOption.ts, website/src/views/pageStateHandlers/WasapPageStateHandler.ts
resolves #814 
- There is a new `weeklyAndMonthlyDateRangeOptions` function to generate weekly and monthly date range options using labels like `2025-W23` for weeks, and `2025-08` for months.
- There is a `DynamicDateFilter` which takes a field name, looks at the available date range for that field, and then filters down a given list of date range options to the ones that have overlap with the date range of the field.
=> feat(website): more relevant date range options for W-ASAP page

website/routeMocker.ts, website/src/components/pageStateSelectors/DynamicDateFilter.tsx, website/src/components/views/wasap/WasapPage.tsx, website/src/lapis/getDateRange.spec.ts, website/src/lapis/getDateRange.ts, website/src/lapis/getMutations.spec.ts, website/src/lapis/getMutations.ts, website/src/lapis/getTotalCount.ts, website/src/types/wastewaterConfig.ts
- moves the `fetchMutations` function into `getMutations` in the `lapis` package; there are already other fns like it.
- Also add response schema and testing, better error handling, mocking.
- adds documentation
n/a
=> refactor(website): move lapis functions into common package

website/routeMocker.ts, website/src/components/pageStateSelectors/WasapPageStateSelector.tsx, website/src/components/views/wasap/WasapPage.tsx, website/src/lapis/getCladeLineages.spec.ts, website/src/lapis/getCladeLineages.ts, website/src/lapis/getDateRange.ts, website/src/lapis/types.ts, website/src/types/wastewaterConfig.ts, website/src/views/pageStateHandlers/WasapPageStateHandler.ts
resolves #818 
- adds a new lapis fetch function that gets the mapping from clade to lineage (with test)
- refactor the UI, so you can explicitly select the Nextstrain clades, or add your own list. The new UI also makes it clear that the list is coming from Nextstrain, and makes it easier to "go back" to that list, in case you edited it.
https://github.com/user-attachments/assets/64bd35e4-89b3-4ef4-9ecb-2e15858f2267
=> feat(website): define  untracked exclusion list dynamically

website/src/components/pageStateSelectors/WasapPageStateSelector.tsx
resolves #807 
- Adds an input field above the slider
The issue description mentions that the range is not indicated, but by sliding to both ends of the slider, you know the range. The design looks similar to https://components.genspectrum.org/?path=/story/input-number-range-filter--default - which also doesn't have start and end labels.
=> feat(website): add number fields to the sliders on the W-ASAP dashboard

website/src/views/pageStateHandlers/WasapPageStateHandler.ts
This sets Zürich as the default city that we filter for.
Now the state to not filter for any city also cannot be represented anymore, so it becomes impossible to not filter for a city.
But I've been told that this is actually fine, because it makes no sense to put all data from all cities together.
n/a
=> feat(website): for W-ASAP set Zürich as the default city to filter for
